-- YatraSetu Complete Madhya Pradesh Tourism Dataset (Famous Highlights & Hidden Gems)
-- Version 3.0 - Full Provenance & Verified Image Metadata

INSERT INTO public.destinations (id, name, slug, description, latitude, longitude, category, region, hero_image_url, image_source, image_source_url, image_alt, image_credit, image_license, image_verified_at, road_condition, safety_tips)
VALUES
(
    'a1111111-1111-1111-1111-111111111111',
    'Pachmarhi (Queen of Satpura)',
    'pachmarhi',
    'A pristine hill station nestled in the Satpura range, famed for cascading waterfalls like Bee Falls, prehistoric cave paintings at Pandav Caves, sunset viewpoints at Dhoopgarh, and tranquil pine forests.',
    22.4674,
    78.4346,
    'Hill Station & Nature',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    'Madhya Pradesh Tourism Board',
    'https://www.mptourism.com/destination-pachmarhi.php',
    'Bee Falls cascading through lush Satpura valley rocks in Pachmarhi',
    'MP Tourism / Satpura Ecotourism',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Scenic ghat roads from Pipariya; well-maintained asphalt with hairpin curves. Low gears recommended on descents.',
    '["Maintain low gears on ghat descents; avoid excessive braking", "Forest entry permit required for core reserve zones and Dhoopgarh", "Pre-book forest gypsy safari for Bee Falls and Duchess Falls"]'::jsonb
),
(
    'c3333333-3333-3333-3333-333333333333',
    'Sanchi Stupa & Archaeological Complex',
    'sanchi',
    'One of India''s oldest stone structures commissioned by Emperor Ashoka in the 3rd century BCE, representing timeless Buddhist art, ornate Toranas, and monastic legacy.',
    23.48,
    77.74,
    'UNESCO Heritage & History',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India (ASI) / UNESCO',
    'https://whc.unesco.org/en/list/524/',
    'The Great Sanchi Stupa showing detailed Ashokan stone Torana gateway carvings',
    'ASI / UNESCO World Heritage',
    'World Heritage Public Domain / CC-BY-SA',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Direct 4-lane SH 19 / NH 146 highway from Bhopal (approx 46 km); dual carriageway with smooth tarmac.',
    '["Electric golf carts available on campus for elderly visitors", "ASI museum is closed on Fridays", "Ideal for early morning or sunset visits to avoid midday sun"]'::jsonb
),
(
    '88888888-8888-8888-8888-888888888888',
    'Bhimbetka Rock Shelters',
    'bhimbetka',
    'An extraordinary UNESCO World Heritage site displaying human rock paintings over 30,000 years old, depicting prehistoric dance, hunting, and daily life on sandstone bluffs.',
    22.9372,
    77.6128,
    'Prehistoric Archaeology & Caves',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1508873696983-2df5703bc20d?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India (ASI)',
    'https://whc.unesco.org/en/list/925/',
    'Prehistoric red and white cave rock paintings at Bhimbetka Rock Shelters',
    'ASI Bhimbetka Heritage Circle',
    'World Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Directly off NH 46 (Bhopal-Hoshangabad highway) approx 45 km; quick turnoff with paved access road.',
    '["Short 1.5 km walking trail across rock clusters; wear sturdy footwear", "Guide audio devices available at entry kiosk", "Stay on paved paths to protect delicate prehistoric art"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000001',
    'Bhojpur Shiva Temple (Bhojeshwar)',
    'bhojpur',
    'An architectural marvel founded by Raja Bhoj in the 11th century, housing one of the world''s tallest monolithic Shiva Lingams (7.5 ft) set on a grand 21 ft platform.',
    23.1,
    77.5833,
    'Ancient Architecture & Spiritual',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India (ASI)',
    'https://www.mptourism.com/destination-bhojpur.php',
    'Massive monolithic stone sanctum and entrance dome of Bhojpur Shiva Temple',
    'MP Tourism / ASI Central Circle',
    'State Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Smooth 28 km state road connecting from Bhopal via 11 Mile bypass; accessible for all vehicles.',
    '["Betwa riverbank nearby has rocky terrain; avoid swimming during monsoons", "Stone steps inside the sanctum can be slippery during aarti times", "Combines well with a day trip to Bhimbetka"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000002',
    'Raisen Hilltop Fortress',
    'raisen-fort',
    'A dramatic 800-year-old hilltop citadel with massive stone ramparts, 9 gateways, 40 rock-cut wells, an ancient Shiva temple, and a cliffside shrine overlooking panoramic plains.',
    23.3323,
    77.7816,
    'Historical Fortress & Viewpoint',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    'Madhya Pradesh Directorate of Archaeology',
    'https://raisen.nic.in/en/tourist-place/raisen-fort/',
    'Ancient stone ramparts and watchtowers of Raisen Hilltop Fortress',
    'District Administration Raisen / MP Tourism',
    'Public Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km east of Bhopal via NH 146; steep paved ramp road leads to fort gate with parking.',
    '["Requires 20-30 minutes uphill walking through stone gates", "Carry sufficient drinking water as uphill stalls are limited", "Evening sunset offers spectacular 360-degree photography"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000003',
    'Ratapani Tiger Reserve & Delawadi',
    'ratapani',
    'A dense teak jungle and wildlife reserve spreading across the Vindhyan hills, featuring secluded water reservoirs, wild leopards, tigers, sloth bears, and prehistoric rock art.',
    22.842,
    77.585,
    'Wildlife Safari & Forest Retreat',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'Madhya Pradesh Forest Department',
    'https://forest.mponline.gov.in/',
    'Teak forest safari track and wildlife waterhole in Ratapani Sanctuary',
    'MP Forest Department / Ecotourism Board',
    'Official Wildlife Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    'NH 46 to Obaidullaganj then forest road through Delawadi; high ground clearance / SUV recommended for deep tracks.',
    '["Strict forest department permits required for jeep safaris", "Do not venture into forest trails on foot without a designated ranger", "Check gate opening hours before planning early morning drives"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000004',
    'Islamnagar & Chaman Mahal',
    'islamnagar',
    'A hidden Afghan-Mughal garden palace established in 1715 by Dost Mohammad Khan, showcasing charbagh gardens, sandstone pavilions, ornate sheesh mahals, and lotus fountains.',
    23.36,
    77.41,
    'Hidden Heritage & Mughal Gardens',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    'Madhya Pradesh State Archaeology',
    'https://bhopal.nic.in/en/tourist-place/chaman-mahal-islamnagar/',
    'Chaman Mahal charbagh garden pavilions and red sandstone corridors',
    'MP Archaeology / Bhopal Heritage',
    'State Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Quick 14 km drive north of Bhopal along Berasia road; well-paved village road.',
    '["Open from sunrise to sunset under MP Archaeology protection", "Very peaceful, uncrowded alternative for history and photography buffs", "Combine with a visit to Halali Dam nearby"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000005',
    'Halali Dam & Backwaters',
    'halali-dam',
    'A massive reservoir on the Halali river surrounded by gentle green hills, offering boat rides, water birds, fishing, and a serene MP Tourism lakeside resort.',
    23.5042,
    77.555,
    'Lakeside Retreat & Water Sports',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    'MP Tourism Water Sports & Resorts',
    'https://www.mptourism.com/destination-halali.php',
    'Halali reservoir lake waters and MP Tourism boat dock',
    'MP State Tourism Development Corporation',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '40 km from Bhopal via Bhopal-Vidisha highway; good state road connecting right to the resort gates.',
    '["Boating available through MP Tourism boat club", "Swimming in deep dam waters without life jackets is strictly prohibited", "Monsoon and post-monsoon (August-January) offer full water levels"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000006',
    'Kerwa & Kaliasot Eco-Adventure Zone',
    'kerwa-dam',
    'A nature and adventure hub located on the southwestern fringe of Bhopal, famous for nature trails, India''s longest twin zip line across water, and birdwatching.',
    23.161,
    77.375,
    'Adventure & Nature Escape',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    'MP Ecotourism Development Board',
    'https://www.mptourism.com/destination-kerwa.php',
    'Green forested hills and lake waters at Kerwa Eco-Adventure Zone',
    'MP Ecotourism Board',
    'State Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '15 km from Bhopal city center; smooth asphalt road winding through green hills.',
    '["Zipline and rope activities operate under certified instructors", "Forest edge territory; avoid solitary hikes after sunset", "Excellent spot for morning cycling and weekend drives"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000007',
    'Madhai & Satpura Tiger Reserve Backwaters',
    'madhai-satpura',
    'An offbeat ecotourism sanctuary offering silent motorless canoe safaris across Denwa backwaters, walking jungle patrols, and pristine teak wilderness away from crowd trails.',
    22.58,
    77.98,
    'Wildlife Safari & River Backwaters',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'Satpura Tiger Reserve Authority',
    'https://forest.mponline.gov.in/',
    'Denwa river canoe crossing overlooking Satpura national park hills at Madhai',
    'Satpura Tiger Reserve / MP Forest',
    'Official Wildlife Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Bhopal to Sohagpur via NH 46 & SH 22 (approx 140 km), followed by a 18 km forest road to Denwa river bank.',
    '["Vehicles park on the outer river bank; boat transfer required to enter core park", "Night safaris on the buffer zone provide unique sloth bear sightings", "Advanced safari booking required through MP Online portal"]'::jsonb
),
(
    'd4444444-4444-4444-4444-444444444444',
    'Mandu (City of Joy / Mandavgad)',
    'mandu',
    'A ruined medieval fortress city celebrated for Afghan architecture, the floating Jahaz Mahal, Hindola Mahal, Rani Roopmati Pavilion, and baobab trees perched on the Vindhya crest.',
    22.366,
    75.343,
    'Historical Citadel & Romantic Heritage',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India / MP Tourism',
    'https://www.mptourism.com/destination-mandu.php',
    'Jahaz Mahal palace structure reflected in the reservoir waters at Mandu',
    'ASI / MP Tourism',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approached via Dhar/Indore (95 km) through smooth state highways with scenic plateau winding roads.',
    '["Bicycle and e-bike rentals available at monument gates", "Monsoon season (July-October) offers misty clouds and peak greenery", "Watch for steep stone staircases in ancient pavilions"]'::jsonb
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Maheshwar Holy Ghats & Ahilya Fort',
    'maheshwar',
    'A tranquil spiritual town on the sacred Narmada river, renowned for Rani Ahilyabai Holkar''s stone palace, traditional handloom Maheshwari weaving, and ancient temple ghats.',
    22.179,
    75.584,
    'Culture, Weaving Heritage & Spiritual',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1609743522653-52354461eb27?auto=format&fit=crop&w=1200&q=80',
    'Ahilya Fort Heritage Trust & MP Tourism',
    'https://www.mptourism.com/destination-maheshwar.php',
    'Stone temple ghats and Ahilya Fort overlooking the wide sacred Narmada River',
    'MP Tourism / Ahilya Heritage',
    'Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '90 km from Indore via AB Road and Dhamnod bypass; smooth 4-lane expressway and rural connector.',
    '["Visit Rehwa Society inside fort complex for live master handloom weaving", "Sunset wooden boat ride to Baneshwar temple in mid-river is highly recommended", "Morning ghat walks are peaceful and serene"]'::jsonb
),
(
    '99999999-9999-9999-9999-999999999999',
    'Ujjain Mahakal & Shri Mahakal Mahalok',
    'ujjain',
    'One of the seven sacred Moksha puris in India, home to the revered Mahakaleshwar Jyotirlinga, the grand 900m Shri Mahakal Mahalok corridor, and Ram Ghat on the sacred Shipra.',
    23.1765,
    75.7885,
    'Pilgrimage & Spiritual Culture',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=1200&q=80',
    'Shri Mahakaleshwar Temple Management Committee',
    'https://shrimahakaleshwar.com/',
    'Night illuminated corridor of Shri Mahakal Mahalok in Ujjain',
    'Ujjain Smart City / Temple Trust',
    'Official Shrine Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Indore-Ujjain 4-lane expressway (SH 27) approx 55 km; high capacity transit with multiple rest plazas.',
    '["Bhasma Aarti pre-booking required on official shrine portal", "Battery e-rickshaws operate throughout the Mahakal corridor", "Evening Shipra River Aarti begins around sunset at Ram Ghat"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000001',
    'Omkareshwar Island & Jyotirlinga',
    'omkareshwar',
    'A revered pilgrimage island in the Narmada River shaped naturally like the sacred ''Om'' symbol (Mandhata Island), home to the ancient Omkareshwar and Mamleshwar shrines.',
    22.2464,
    76.1511,
    'Pilgrimage & Sacred Island',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80',
    'Shri Omkareshwar Temple Trust / MP Tourism',
    'https://www.mptourism.com/destination-omkareshwar.php',
    'Sacred Mandhata island and Narmada ghat temples with suspension bridge',
    'MP Tourism / Temple Board',
    'Verified Pilgrimage Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    '77 km south of Indore via Khandwa Road (SH 27); well-paved road with scenic Narmada valley ghats.',
    '["Suspension bridges (Jhula Pul) connect mainland to the island", "Island parikrama (circumnavigation) trail is 7 km; start early morning", "Life jackets mandatory during motorized boat crossings"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000002',
    'Patalpani Waterfall & Heritage Railway Gorge',
    'patalpani',
    'A picturesque 300-foot waterfall cascading into a deep mythical gorge near Mhow, surrounded by lush green valleys and traversed by India''s oldest scenic metre-gauge heritage train.',
    22.502,
    75.798,
    'Monsoon Waterfall & Scenic Gorge',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    'Western Railway Heritage / MP Tourism',
    'https://www.mptourism.com/destination-indore.php',
    'Patalpani waterfall plunging into misty forest canyon during monsoon',
    'MP Tourism Eco Wing',
    'Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '35 km from Indore via Mhow; smooth paved road up to the waterfall overlook viewpoint.',
    '["Flash floods occur suddenly in rainy season; strictly obey barrier warnings", "Never attempt descending to the bottom of the gorge pool during monsoons", "Heritage train rides from Patalpani to Kalakund operate on weekends"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000003',
    'Choral Dam & Backwater Resort',
    'choral-dam',
    'A tranquil green reservoir surrounded by low hills of the Vindhyan range, ideal for weekend picnics, paddle boating, birdwatching, and peaceful rural retreats.',
    22.42,
    75.76,
    'Eco-Retreat & Water Leisure',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    'MP Tourism Resorts',
    'https://www.mptourism.com/destination-choral.php',
    'Choral Dam serene reservoir waters and green hill slopes',
    'MPSTDC Choral Resort',
    'Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km from Indore on Khandwa road; scenic winding road through green hills.',
    '["MP Tourism operates a serene tourist bungalow on the reservoir bank", "Pedal and motor boats available with safety gear", "Great stopover on the way to Omkareshwar"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000004',
    'Janapav Kuti (Parshuram Birthplace)',
    'janapav',
    'The highest peak of the Malwa plateau (881m) and traditional birthplace of Lord Parshuram, where twelve rivers are believed to originate amidst misty hilltop forests.',
    22.46,
    75.68,
    'Hilltop Viewpoint & Spiritual Trek',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    'Indore District Tourism Promotion Council',
    'https://indore.nic.in/en/tourist-place/janapav/',
    'Lush misty green peaks and valley overlook from Janapav Kuti summit',
    'District Administration Indore / MP Tourism',
    'Public Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km from Indore directly off Mumbai-Agra NH 52; steep paved winding road to summit.',
    '["Summit road has sharp curves; drive cautiously in heavy fog", "Panoramic 360-degree viewpoint overlooking Malwa plains", "Ayurvedic herbs and ashram atmosphere on hilltop"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000005',
    'Burhanpur Shahi Qila & Asirgarh Fortress',
    'burhanpur-asirgarh',
    'The historic ''Gateway to the Deccan'' featuring the invincible Asirgarh hilltop fort, Mughal bathhouses (Shahi Hammam), black stone Jama Masjid, and the unique underground Kundi Bhandara water system.',
    21.31,
    76.22,
    'Mughal Architecture & Massive Fort',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India / MP Tourism',
    'https://burhanpur.nic.in/en/tourist-place/asirgarh-fort/',
    'Asirgarh hilltop stone fortress battlements overlooking Satpura valleys',
    'ASI Bhopal Circle / Burhanpur Tourism',
    'State Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '180 km from Indore via Sanawad & Khandwa (SH 27 / NH 347); smooth state highway.',
    '["Asirgarh fort is expansive; carry sun protection and comfortable walking shoes", "UNESCO tentative listed underground water labyrinth Kundi Bhandara is a must-see", "Sample authentic Burhanpuri Mawa Jalebi and Daraba sweet in local markets"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000006',
    'Gandhi Sagar Sanctuary & Hinglajgarh Fort',
    'gandhi-sagar',
    'An offbeat wildlife haven along the Chambal river reservoir in Mandsaur, featuring rock-cut temples, prehistoric rock art, Hinglajgarh forest citadel, and boat safaris for marsh crocodiles and leopards.',
    24.58,
    75.65,
    'Hidden Wildlife Sanctuary & Canyon',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'MP Tourism / Gandhi Sagar Festival',
    'https://www.mptourism.com/destination-gandhisagar.php',
    'Chambal river reservoir water canyons and wildlife forest edge at Gandhi Sagar',
    'MP Tourism Ecotourism Wing',
    'Official Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Mandsaur/Neemuch to Bhanpura via SH; rugged scenic landscape with paved access.',
    '["Annual Gandhi Sagar Floating Festival operates luxury tent cities and water sports", "Hire registered forest guides for rock art site visits", "Winter season (Nov-Feb) brings thousands of migratory aquatic birds"]'::jsonb
),
(
    'e5555555-5555-5555-5555-555555555555',
    'Bhedaghat & Marble Rocks',
    'bhedaghat',
    'Towering crystalline marble cliffs rising 100 feet on either side of the sacred Narmada River, creating the roaring Dhuandhar Falls, cable ropeway, and serene moonlight boat gorges.',
    23.1311,
    79.8006,
    'Geological Wonder & River Gorge',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    'Jabalpur Tourism Promotion Council / MP Tourism',
    'https://www.mptourism.com/destination-bhedaghat.php',
    'Crystalline white marble cliffs and boat gorge along the Narmada at Bhedaghat',
    'MP Tourism Jabalpur Wing',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Fast 22 km highway drive from Jabalpur city center; broad bypass road with smooth tarmac.',
    '["Boating is suspended during peak monsoon flood currents (July-Sept)", "Full moon night boat rides through the marble canyon are extraordinarily popular", "Cable car ropeway connects both banks directly above Dhuandhar falls"]'::jsonb
),
(
    '77777777-7777-7777-7777-777777777777',
    'Kanha National Park & Tiger Reserve',
    'kanha',
    'Vast Sal forests and sweeping meadows that inspired Rudyard Kipling''s Jungle Book, hosting flourishing populations of Royal Bengal Tigers and the rare Hardground Barasingha (swamp deer).',
    22.3345,
    80.6115,
    'Wildlife Safari & Tiger Reserve',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'Kanha Tiger Reserve Field Directorate',
    'https://kanhatigerreserve.org/',
    'Royal Bengal tiger moving through open Sal meadows in Kanha National Park',
    'Kanha Tiger Reserve Authority / MP Forest',
    'Official Tiger Reserve Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Good state highway from Jabalpur (160 km) and Raipur; forest fringe roads require slow cautious driving.',
    '["Park closed July 1 to Sept 30 during annual breeding season", "Safari slots across Khatia, Mukki, and Sarhi gates must be booked in advance", "Morning safaris require early 5:30 AM reporting at designated gates"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000001',
    'Bandhavgarh National Park',
    'bandhavgarh',
    'Famous for having one of the highest densities of Royal Bengal Tigers in the world, centered around an ancient 2,000-year-old hilltop fort and reclining Vishnu rock sculpture (Shesh Shaiya).',
    23.7225,
    81.025,
    'Wildlife Safari & Ancient Citadel',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'Bandhavgarh Tiger Reserve Authority',
    'https://forest.mponline.gov.in/',
    'Bandhavgarh cliff fortress backdrop with tiger habitat grasslands in foreground',
    'Bandhavgarh Field Directorate / MP Forest',
    'Official Reserve Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    '165 km from Jabalpur via Katni / Umaria; 4-lane highway with good connectivity.',
    '["Tala, Magdhi, and Khitauli are the prime safari zones", "Pre-booking open gypsy vehicles is essential for tiger tracking", "Carry warm clothing during November-February morning safaris"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000002',
    'Pench National Park (Mowgli''s Land)',
    'pench',
    'The classic landscape of teak forests and the meandering Pench River, renowned for tiger tracking, leopard sightings, Indian wild dogs (Dhole), and wolf sanctuaries.',
    21.75,
    79.3,
    'Wildlife Safari & Ecotourism',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'Pench Tiger Reserve Directorate',
    'https://penchtiger.mponline.gov.in/',
    'Teak forest tree canopy and riverbed clearing in Pench National Park',
    'Pench Tiger Reserve Authority',
    'Official Park Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Directly accessible from Seoni and Nagpur via NH 44 (four-lane expressway with wildlife elevated corridor).',
    '["Turia and Karmajhiri are the most popular entry gates", "Night buffer safaris offer nocturnal wildlife viewing", "Check gate locations when booking lodging accommodations"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000003',
    'Amarkantak (Teerthraj / Source of Narmada)',
    'amarkantak',
    'The sacred meeting point of the Vindhya and Satpura ranges, source of the Holy Narmada and Son rivers, featuring the Narmadakund temple complex, Kapildhara waterfall, and Mai ki Bagiya.',
    22.67,
    81.75,
    'Sacred Source & Mountain Sanctuary',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80',
    'Amarkantak Temple Trust / MP Tourism',
    'https://www.mptourism.com/destination-amarkantak.php',
    'White-washed temple shrines surrounding the sacred Narmadakund in Amarkantak',
    'MP Tourism / Holy Shrine Board',
    'Pilgrimage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Scenic ghat road from Jabalpur (220 km) or Shahdol; pine tree lined hill ascent with smooth asphalt.',
    '["Temperatures remain pleasant year-round; carry light woolens in winter", "Kapildhara and Dudhadhara waterfalls require moderate walking downhill", "Visit Kabir Chabutra for sunset views across valley ridges"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000004',
    'Patalkot Valley & Tamia Hills',
    'patalkot-tamia',
    'A secluded 1,200-foot-deep horseshoe-shaped canyon in Chhindwara, home to indigenous Bharia tribes, 18 isolated villages, untouched flora, and rare ethno-medicinal herbs.',
    22.4,
    78.75,
    'Hidden Canyon & Tribal Eco-Heritage',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    'Chhindwara District Administration / MP Tourism',
    'https://chhindwara.nic.in/en/tourist-place/patalkot/',
    'Deep dramatic green gorge and isolated tribal settlement basin in Patalkot Valley',
    'MP Ecotourism / Chhindwara Tribal Council',
    'Tribal Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '78 km northwest of Chhindwara via Tamia ghats; winding hill roads with breathtaking valley lookouts.',
    '["Hiring a local tribal guide is mandatory for descending into the valley basin", "Sunlight reaches the deep canyon floor only for a few hours around midday", "Tamia PWD Rest House offers one of MP''s best cliffside sunrise views"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000005',
    'Bargi Dam & Narmada Water Cruises',
    'bargi-dam',
    'One of the first major dams on the Narmada River near Jabalpur, featuring speedboating, water scooters, luxury cruise liners, and the scenic Maikhali Island resort.',
    22.95,
    79.88,
    'Lake Cruise & Water Adventures',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    'MP Tourism Water Sports Complex',
    'https://www.mptourism.com/destination-bargi.php',
    'Bargi Dam reservoir water sports complex and cruise ship on Narmada waters',
    'MPSTDC Bargi Resort',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '40 km from Jabalpur along NH 44 / Mandla road; smooth highway transit.',
    '["Cruise rides to Mandla operate during high reservoir water levels", "MP Tourism water sports complex provides certified life jackets", "Spectacular sunset dining on the cruise boat"]'::jsonb
),
(
    'b2222222-2222-2222-2222-222222222222',
    'Khajuraho Group of Monuments',
    'khajuraho',
    'A world-renowned UNESCO World Heritage site known for magnificent Nagara-style architectural temples, intricate stone carvings, and the annual Khajuraho Dance Festival.',
    24.8318,
    79.9199,
    'UNESCO Heritage & Architecture',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India / UNESCO',
    'https://whc.unesco.org/en/list/240/',
    'Kandariya Mahadeva Temple Nagara shikhara and stone relief friezes in Khajuraho',
    'ASI / UNESCO World Heritage',
    'World Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'NH 39 four-lane highway connectivity from Jhansi and Chhatarpur; smooth transit suitable for all vehicles.',
    '["Western group of temples requires ASI entry ticket", "Light and Sound show operates in evening hours (English & Hindi)", "Summer temperatures can exceed 42\u00b0C; carry hydration and sun protection"]'::jsonb
),
(
    'f6666666-6666-6666-6666-666666666666',
    'Orchha Historic Royal Town',
    'orchha',
    'A frozen-in-time riverside kingdom founded in the 16th century, featuring the grand Jahangir Mahal, Raja Mahal, Ram Raja Temple (where Rama is worshipped as King), and riverside Chhatris.',
    25.351,
    78.6433,
    'Palatial Heritage & Riverside Culture',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    'Madhya Pradesh State Archaeology / MP Tourism',
    'https://www.mptourism.com/destination-orchha.php',
    'Royal stone Chhatris and Jahangir Mahal reflected in the Betwa River in Orchha',
    'MP Tourism / Orchha Heritage',
    'State Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Easy 15 km drive from Jhansi railway hub; wide paved road connecting across the Betwa river.',
    '["River rafting and kayaking available on the Betwa in post-monsoon months", "Ram Raja Temple follows royal guard of honour salute during daily aarti", "Sound and light show inside Orchha Fort palace complex"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000001',
    'Gwalior Fort & Gopachal Rock Statues',
    'gwalior-fort',
    'Referred to as ''The Pearl in the necklace of forts of India'' by Babur, perched atop a steep sandstone hill with Man Mandir Palace, Sas Bahu Temples, Teli ka Mandir, and giant 7th-century rock-cut Jain Tirthankaras.',
    26.2295,
    78.167,
    'Hill Fortress & Ancient Citadel',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India / Gwalior Heritage',
    'https://gwalior.nic.in/en/tourist-place/gwalior-fort/',
    'Man Mandir Palace sandstone battlements and ornate turquoise tile frieze at Gwalior Fort',
    'ASI / MP Tourism',
    'National Monument Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Direct 6-lane NH 44 connectivity; smooth uphill climb to the fort gate from Urvai Gate or Gwalior Gate.',
    '["Urvai Gate ascent allows driving cars up to the fort summit parking", "Visit Jai Vilas Palace and Scindia Museum in the city below", "Evening sound and light show narrated by Amitabh Bachchan"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000002',
    'Mitawali, Padhavali & Bateshwar Temples',
    'mitawali-bateshwar',
    'An astonishing archaeological triangle in Morena featuring the circular Chausath Yogini temple (inspiration for India''s Parliament House), the fortified Padhavali palace, and over 200 restored 8th-century Gurjara-Pratihara temples.',
    26.43,
    78.22,
    'Hidden Archaeological Wonder',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India (ASI Bhopal Circle)',
    'https://morena.nic.in/en/tourist-place/mitawali-temple/',
    'Circular pillared hypaethral colonnade of Chausath Yogini Temple at Mitawali',
    'ASI Archaeological Conservation Team',
    'ASI Monument Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '35 km northeast of Gwalior via Malanpur / Rithora; paved rural roads with light village traffic.',
    '["Climbing 100 stairs required to reach circular Mitawali temple atop the hill", "ASI restoration of Bateshwar temple complex is one of India''s archaeological triumphs", "Visit during daytime hours (9 AM to 5 PM)"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000003',
    'National Chambal Wildlife Sanctuary',
    'chambal-sanctuary',
    'A pristine river reserve dedicated to the critically endangered Gharial (fish-eating crocodile), Red-crowned roof turtle, Gangetic river dolphins, and exotic skimmer birds navigating deep sand ravines.',
    26.65,
    78.55,
    'River Wildlife & Endangered Species',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
    'National Chambal Sanctuary Forest Wing',
    'https://forest.mponline.gov.in/',
    'Chambal river sandbars and deep clay ravines sheltering endangered Gharials',
    'MP & UP Wildlife Department',
    'Wildlife Sanctuary Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    '70 km from Gwalior / 100 km from Agra; paved access to the official forest boat ghat.',
    '["Motorboat safaris with forest department naturalist are compulsory", "Winter months (Nov-March) offer ideal basking crocodile sightings", "Follow eco-tourism rules; do not litter or make loud noise along river sandbars"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000004',
    'Raneh Falls & Ken River Crystalline Canyon',
    'raneh-falls',
    'India''s own ''Grand Canyon'' - a 30-meter-deep gorge carved by the Ken River through volcanic rock displaying five pure shades of granite (pink, green, red, grey, and black) with cascading seasonal waterfalls.',
    24.89,
    79.98,
    'Geological Canyon & Waterfall',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    'Ken Ghariyal Sanctuary / MP Tourism',
    'https://www.mptourism.com/destination-raneh-falls.php',
    'Deep volcanic pink and green crystalline granite gorge and canyon at Raneh Falls',
    'MP Tourism / Forest Department',
    'State Geological Reserve',
    '2026-08-21T06:00:00Z'::timestamptz,
    '20 km from Khajuraho through Panna Tiger Reserve buffer; well-maintained forest approach road.',
    '["Entry permit issued at Ken Ghariyal Sanctuary gate", "Best visited during post-monsoon (August-January) when canyon waters flow vigorously", "Viewpoints are securely railed for visitor safety"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000005',
    'Chanderi Heritage Town & Weaving Cluster',
    'chanderi',
    'An ancient fortified town surrounded by hills and lakes, celebrated for handwoven Chanderi silk sarees, the grand Koshak Mahal, Badal Mahal Gate, and the hilltop Chanderi Fort.',
    24.715,
    78.135,
    'Silk Weaving Heritage & Fortified Town',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1609743522653-52354461eb27?auto=format&fit=crop&w=1200&q=80',
    'Chanderi Handloom Weavers Guild / MP Tourism',
    'https://www.mptourism.com/destination-chanderi.php',
    'Badal Mahal monumental stone gateway with hilltop Chanderi fort in background',
    'MP Tourism / Chanderi Craft Council',
    'Craft & Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '110 km from Jhansi / 210 km from Bhopal via Lalitpur or Ashoknagar; good state highways.',
    '["Explore Pranpur craft village for live traditional loom demonstrations", "Chanderi Fort offers stunning sunset views over the whitewashed historic town", "Chanderi Museum preserves exquisite sculptures and ancient coins"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000006',
    'Datia Pitambara Peeth & Bir Singh Palace',
    'datia-palace',
    'A blend of spiritual devotion and monumental 17th-century Bundela architecture in the Govind Mahal (7-storey stone palace built entirely without wood or iron beams) and the revered Baglamukhi shrine.',
    25.6667,
    78.46,
    'Bundela Architecture & Shakti Peeth',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    'Archaeological Survey of India / MP Tourism',
    'https://datia.nic.in/en/tourist-place/bir-singh-palace/',
    'Seven-storey sandstone royal palace of Bir Singh Dev at Datia',
    'ASI / Datia District Administration',
    'National Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Directly on NH 44 between Gwalior (75 km) and Jhansi (30 km); fast 4-lane highway.',
    '["Bir Singh Palace is an architectural marvel with intricate symmetry and wall frescoes", "Pitambara Peeth attracts large pilgrimage gatherings on Saturdays and Navratri", "Easy half-day stopover on the Gwalior-Orchha transit route"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000007',
    'Panna National Park & Diamond Mines',
    'panna-tiger-reserve',
    'A successful tiger conservation story along the Ken River gorge, known for boat safaris, tree-nesting vulture colonies, pristine Pandav Falls, and India''s only active diamond mining belt.',
    24.65,
    80.05,
    'Tiger Reserve, Gorge & Diamond Valley',
    'Madhya Pradesh',
    'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    'Panna Tiger Reserve Directorate',
    'https://forest.mponline.gov.in/',
    'Ken river flowing through rocky gorges in Panna Tiger Reserve',
    'Panna Field Directorate / MP Forest',
    'Tiger Reserve Official',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km from Khajuraho via NH 39; smooth tarmac road right to Madla entrance gate.',
    '["Madla and Hinouta gates provide deep forest safari access", "Boat ride on the Ken River within the park offers unique crocodile sightings", "Combine with Pandav Falls caves and Raneh Falls on the same circuit"]'::jsonb
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    category = EXCLUDED.category,
    region = EXCLUDED.region,
    hero_image_url = EXCLUDED.hero_image_url,
    image_source = EXCLUDED.image_source,
    image_source_url = EXCLUDED.image_source_url,
    image_alt = EXCLUDED.image_alt,
    image_credit = EXCLUDED.image_credit,
    image_license = EXCLUDED.image_license,
    image_verified_at = EXCLUDED.image_verified_at,
    road_condition = EXCLUDED.road_condition,
    safety_tips = EXCLUDED.safety_tips,
    updated_at = NOW();
