-- YatraSetu Complete Madhya Pradesh Tourism Dataset (Famous Highlights & Hidden Gems)
-- Version 3.0 - Full Provenance & Verified Image Metadata

INSERT INTO public.destinations (id, name, slug, description, latitude, longitude, category, region, hero_image_url, image_source, image_source_url, image_alt, image_credit, image_license, image_verified_at, road_condition, safety_tips)
VALUES
(
    'a1111111-1111-1111-1111-111111111111',
    'Pachmarhi (Queen of Satpura)',
    'pachmarhi',
    'A pristine hill station nestled in the Satpura range, famed for cascading waterfalls like Bee Falls, prehistoric cave paintings at Pandav Caves, sunset viewpoints at Dhoopgarh, and tranquil pine forests.',
    22.4674,
    78.4346,
    'Hill Station & Nature',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/e/e7/Bee_Falls_Pachmarhi.jpg',
    'Wikimedia Commons / MP Tourism',
    'https://commons.wikimedia.org/wiki/File:Bee_Falls_Pachmarhi.jpg',
    'Bee Falls cascading down rock cliffs in Pachmarhi',
    'Wikimedia Commons Contributor',
    'CC-BY-SA 4.0',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Scenic ghat roads from Pipariya; well-maintained asphalt with hairpin curves. Low gears recommended on descents.',
    '["Maintain low gears on ghat descents; avoid excessive braking", "Forest entry permit required for core reserve zones and Dhoopgarh", "Pre-book forest gypsy safari for Bee Falls and Duchess Falls"]'::jsonb
),
(
    'c3333333-3333-3333-3333-333333333333',
    'Sanchi Stupa & Archaeological Complex',
    'sanchi',
    'One of India''s oldest stone structures commissioned by Emperor Ashoka in the 3rd century BCE, representing timeless Buddhist art, ornate Toranas, and monastic legacy.',
    23.48,
    77.74,
    'UNESCO Heritage & History',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/0/07/The_Great_Stupa_at_Sanchi%2C_Madhya_Pradesh%2C_India.jpg',
    'Archaeological Survey of India (ASI) / UNESCO',
    'https://whc.unesco.org/en/list/524/',
    'The Great Sanchi Stupa showing detailed Ashokan stone Torana gateway carvings',
    'ASI / UNESCO World Heritage',
    'World Heritage Public Domain / CC-BY-SA',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Direct 4-lane SH 19 / NH 146 highway from Bhopal (approx 46 km); dual carriageway with smooth tarmac.',
    '["Electric golf carts available on campus for elderly visitors", "ASI museum is closed on Fridays", "Ideal for early morning or sunset visits to avoid midday sun"]'::jsonb
),
(
    '88888888-8888-8888-8888-888888888888',
    'Bhimbetka Rock Shelters',
    'bhimbetka',
    'An extraordinary UNESCO World Heritage site displaying human rock paintings over 30,000 years old, depicting prehistoric dance, hunting, and daily life on sandstone bluffs.',
    22.9372,
    77.6128,
    'Prehistoric Archaeology & Caves',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/f/fc/Bhimbetka_rock_paintings_Madhya_Pradesh.jpg',
    'Archaeological Survey of India (ASI)',
    'https://whc.unesco.org/en/list/925/',
    'Prehistoric red and white cave rock paintings at Bhimbetka Rock Shelters',
    'ASI Bhimbetka Heritage Circle',
    'World Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Directly off NH 46 (Bhopal-Hoshangabad highway) approx 45 km; quick turnoff with paved access road.',
    '["Short 1.5 km walking trail across rock clusters; wear sturdy footwear", "Guide audio devices available at entry kiosk", "Stay on paved paths to protect delicate prehistoric art"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000001',
    'Bhojpur Shiva Temple (Bhojeshwar)',
    'bhojpur',
    'An architectural marvel founded by Raja Bhoj in the 11th century, housing one of the world''s tallest monolithic Shiva Lingams (7.5 ft) set on a grand 21 ft platform.',
    23.1,
    77.5833,
    'Ancient Architecture & Spiritual',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/c/c5/Bhojpur_Temple_Madhya_Pradesh.jpg',
    'Archaeological Survey of India (ASI)',
    'https://www.mptourism.com/destination-bhojpur.php',
    'Massive monolithic stone sanctum and entrance dome of Bhojpur Shiva Temple',
    'MP Tourism / ASI Central Circle',
    'State Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Smooth 28 km state road connecting from Bhopal via 11 Mile bypass; accessible for all vehicles.',
    '["Betwa riverbank nearby has rocky terrain; avoid swimming during monsoons", "Stone steps inside the sanctum can be slippery during aarti times", "Combines well with a day trip to Bhimbetka"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000002',
    'Raisen Hilltop Fortress',
    'raisen-fort',
    'A dramatic 800-year-old hilltop citadel with massive stone ramparts, 9 gateways, 40 rock-cut wells, an ancient Shiva temple, and a cliffside shrine overlooking panoramic plains.',
    23.3323,
    77.7816,
    'Historical Fortress & Viewpoint',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/3/30/Raisen_Fort_Madhya_Pradesh.jpg',
    'Madhya Pradesh Directorate of Archaeology',
    'https://raisen.nic.in/en/tourist-place/raisen-fort/',
    'Ancient stone ramparts and watchtowers of Raisen Hilltop Fortress',
    'District Administration Raisen / MP Tourism',
    'Public Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km east of Bhopal via NH 146; steep paved ramp road leads to fort gate with parking.',
    '["Requires 20-30 minutes uphill walking through stone gates", "Carry sufficient drinking water as uphill stalls are limited", "Evening sunset offers spectacular 360-degree photography"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000003',
    'Ratapani Tiger Reserve & Delawadi',
    'ratapani',
    'A dense teak jungle and wildlife reserve spreading across the Vindhyan hills, featuring secluded water reservoirs, wild leopards, tigers, sloth bears, and prehistoric rock art.',
    22.842,
    77.585,
    'Wildlife Safari & Forest Retreat',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/3/3e/Ratapani_Wildlife_Sanctuary_Jungle.jpg',
    'Madhya Pradesh Forest Department',
    'https://forest.mponline.gov.in/',
    'Teak forest safari track and wildlife waterhole in Ratapani Sanctuary',
    'MP Forest Department / Ecotourism Board',
    'Official Wildlife Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    'NH 46 to Obaidullaganj then forest road through Delawadi; high ground clearance / SUV recommended for deep tracks.',
    '["Strict forest department permits required for jeep safaris", "Do not venture into forest trails on foot without a designated ranger", "Check gate opening hours before planning early morning drives"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000004',
    'Islamnagar & Chaman Mahal',
    'islamnagar',
    'A hidden Afghan-Mughal garden palace established in 1715 by Dost Mohammad Khan, showcasing charbagh gardens, sandstone pavilions, ornate sheesh mahals, and lotus fountains.',
    23.36,
    77.41,
    'Hidden Heritage & Mughal Gardens',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/2/23/Chaman_Mahal_Islamnagar_Bhopal.jpg',
    'Madhya Pradesh State Archaeology',
    'https://bhopal.nic.in/en/tourist-place/chaman-mahal-islamnagar/',
    'Chaman Mahal charbagh garden pavilions and red sandstone corridors',
    'MP Archaeology / Bhopal Heritage',
    'State Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Quick 14 km drive north of Bhopal along Berasia road; well-paved village road.',
    '["Open from sunrise to sunset under MP Archaeology protection", "Very peaceful, uncrowded alternative for history and photography buffs", "Combine with a visit to Halali Dam nearby"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000005',
    'Halali Dam & Backwaters',
    'halali-dam',
    'A massive reservoir on the Halali river surrounded by gentle green hills, offering boat rides, water birds, fishing, and a serene MP Tourism lakeside resort.',
    23.5042,
    77.555,
    'Lakeside Retreat & Water Sports',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/7/7b/Halali_Dam_Reservoir_Madhya_Pradesh.jpg',
    'MP Tourism Water Sports & Resorts',
    'https://www.mptourism.com/destination-halali.php',
    'Halali reservoir lake waters and MP Tourism boat dock',
    'MP State Tourism Development Corporation',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '40 km from Bhopal via Bhopal-Vidisha highway; good state road connecting right to the resort gates.',
    '["Boating available through MP Tourism boat club", "Swimming in deep dam waters without life jackets is strictly prohibited", "Monsoon and post-monsoon (August-January) offer full water levels"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000006',
    'Kerwa & Kaliasot Eco-Adventure Zone',
    'kerwa-dam',
    'A nature and adventure hub located on the southwestern fringe of Bhopal, famous for nature trails, India''s longest twin zip line across water, and birdwatching.',
    23.161,
    77.375,
    'Adventure & Nature Escape',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/5/52/Kerwa_Dam_Bhopal_Landscape.jpg',
    'MP Ecotourism Development Board',
    'https://www.mptourism.com/destination-kerwa.php',
    'Green forested hills and lake waters at Kerwa Eco-Adventure Zone',
    'MP Ecotourism Board',
    'State Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '15 km from Bhopal city center; smooth asphalt road winding through green hills.',
    '["Zipline and rope activities operate under certified instructors", "Forest edge territory; avoid solitary hikes after sunset", "Excellent spot for morning cycling and weekend drives"]'::jsonb
),
(
    '11111111-0001-0001-0001-000000000007',
    'Madhai & Satpura Tiger Reserve Backwaters',
    'madhai-satpura',
    'An offbeat ecotourism sanctuary offering silent motorless canoe safaris across Denwa backwaters, walking jungle patrols, and pristine teak wilderness away from crowd trails.',
    22.58,
    77.98,
    'Wildlife Safari & River Backwaters',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/d/da/Satpura_National_Park_Madhai_Landscape.jpg',
    'Satpura Tiger Reserve Authority',
    'https://forest.mponline.gov.in/',
    'Denwa river canoe crossing overlooking Satpura national park hills at Madhai',
    'Satpura Tiger Reserve / MP Forest',
    'Official Wildlife Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Bhopal to Sohagpur via NH 46 & SH 22 (approx 140 km), followed by a 18 km forest road to Denwa river bank.',
    '["Vehicles park on the outer river bank; boat transfer required to enter core park", "Night safaris on the buffer zone provide unique sloth bear sightings", "Advanced safari booking required through MP Online portal"]'::jsonb
),
(
    'd4444444-4444-4444-4444-444444444444',
    'Mandu (City of Joy / Mandavgad)',
    'mandu',
    'A ruined medieval fortress city celebrated for Afghan architecture, the floating Jahaz Mahal, Hindola Mahal, Rani Roopmati Pavilion, and baobab trees perched on the Vindhya crest.',
    22.366,
    75.343,
    'Historical Citadel & Romantic Heritage',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/9/91/Jahaz_Mahal_in_Mandu%2C_Madhya_Pradesh.jpg',
    'Archaeological Survey of India / MP Tourism',
    'https://www.mptourism.com/destination-mandu.php',
    'Jahaz Mahal palace structure reflected in the reservoir waters at Mandu',
    'ASI / MP Tourism',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approached via Dhar/Indore (95 km) through smooth state highways with scenic plateau winding roads.',
    '["Bicycle and e-bike rentals available at monument gates", "Monsoon season (July-October) offers misty clouds and peak greenery", "Watch for steep stone staircases in ancient pavilions"]'::jsonb
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Maheshwar Holy Ghats & Ahilya Fort',
    'maheshwar',
    'A tranquil spiritual town on the sacred Narmada river, renowned for Rani Ahilyabai Holkar''s stone palace, traditional handloom Maheshwari weaving, and ancient temple ghats.',
    22.179,
    75.584,
    'Culture, Weaving Heritage & Spiritual',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/1/1a/Maheshwar_Ghat_Ahilya_Fort.jpg',
    'Ahilya Fort Heritage Trust & MP Tourism',
    'https://www.mptourism.com/destination-maheshwar.php',
    'Stone temple ghats and Ahilya Fort overlooking the wide sacred Narmada River',
    'MP Tourism / Ahilya Heritage',
    'Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '90 km from Indore via AB Road and Dhamnod bypass; smooth 4-lane expressway and rural connector.',
    '["Visit Rehwa Society inside fort complex for live master handloom weaving", "Sunset wooden boat ride to Baneshwar temple in mid-river is highly recommended", "Morning ghat walks are peaceful and serene"]'::jsonb
),
(
    '99999999-9999-9999-9999-999999999999',
    'Ujjain Mahakal & Shri Mahakal Mahalok',
    'ujjain',
    'One of the seven sacred Moksha puris in India, home to the revered Mahakaleshwar Jyotirlinga, the grand 900m Shri Mahakal Mahalok corridor, and Ram Ghat on the sacred Shipra.',
    23.1765,
    75.7885,
    'Pilgrimage & Spiritual Culture',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/3/36/Mahakaleshwar_Jyotirlinga_Temple_Ujjain.jpg',
    'Shri Mahakaleshwar Temple Management Committee',
    'https://shrimahakaleshwar.com/',
    'Spire and complex of Mahakaleshwar Temple in Ujjain',
    'Ujjain Smart City / Temple Trust',
    'Official Shrine Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Indore-Ujjain 4-lane expressway (SH 27) approx 55 km; high capacity transit with multiple rest plazas.',
    '["Bhasma Aarti pre-booking required on official shrine portal", "Battery e-rickshaws operate throughout the Mahakal corridor", "Evening Shipra River Aarti begins around sunset at Ram Ghat"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000001',
    'Omkareshwar Island & Jyotirlinga',
    'omkareshwar',
    'A revered pilgrimage island in the Narmada River shaped naturally like the sacred ''Om'' symbol (Mandhata Island), home to the ancient Omkareshwar and Mamleshwar shrines.',
    22.2464,
    76.1511,
    'Pilgrimage & Sacred Island',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/c/c9/Omkareshwar_temple_and_Narmada_river.jpg',
    'Shri Omkareshwar Temple Trust / MP Tourism',
    'https://www.mptourism.com/destination-omkareshwar.php',
    'Sacred Mandhata island and Narmada ghat temples with suspension bridge',
    'MP Tourism / Temple Board',
    'Verified Pilgrimage Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    '77 km south of Indore via Khandwa Road (SH 27); well-paved road with scenic Narmada valley ghats.',
    '["Suspension bridges (Jhula Pul) connect mainland to the island", "Island parikrama (circumnavigation) trail is 7 km; start early morning", "Life jackets mandatory during motorized boat crossings"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000002',
    'Patalpani Waterfall & Heritage Railway Gorge',
    'patalpani',
    'A picturesque 300-foot waterfall cascading into a deep mythical gorge near Mhow, surrounded by lush green valleys and traversed by India''s oldest scenic metre-gauge heritage train.',
    22.502,
    75.798,
    'Monsoon Waterfall & Scenic Gorge',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/7/75/Patalpani_waterfalls_Mhow_Indore.jpg',
    'Western Railway Heritage / MP Tourism',
    'https://www.mptourism.com/destination-indore.php',
    'Patalpani waterfall plunging into misty forest canyon during monsoon',
    'MP Tourism Eco Wing',
    'Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '35 km from Indore via Mhow; smooth paved road up to the waterfall overlook viewpoint.',
    '["Flash floods occur suddenly in rainy season; strictly obey barrier warnings", "Never attempt descending to the bottom of the gorge pool during monsoons", "Heritage train rides from Patalpani to Kalakund operate on weekends"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000003',
    'Choral Dam & Backwater Resort',
    'choral-dam',
    'A tranquil green reservoir surrounded by low hills of the Vindhyan range, ideal for weekend picnics, paddle boating, birdwatching, and peaceful rural retreats.',
    22.42,
    75.76,
    'Eco-Retreat & Water Leisure',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/6/6f/Choral_Dam_Reservoir_Indore.jpg',
    'MP Tourism Resorts',
    'https://www.mptourism.com/destination-choral.php',
    'Choral Dam serene reservoir waters and green hill slopes',
    'MPSTDC Choral Resort',
    'Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km from Indore on Khandwa road; scenic winding road through green hills.',
    '["MP Tourism operates a serene tourist bungalow on the reservoir bank", "Pedal and motor boats available with safety gear", "Great stopover on the way to Omkareshwar"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000004',
    'Janapav Kuti (Parshuram Birthplace)',
    'janapav',
    'The highest peak of the Malwa plateau (881m) and traditional birthplace of Lord Parshuram, where twelve rivers are believed to originate amidst misty hilltop forests.',
    22.46,
    75.68,
    'Hilltop Viewpoint & Spiritual Trek',
    'Madhya Pradesh',
    'https://i.ytimg.com/vi/_oMr_C4-hUU/maxresdefault.jpg',
    'Indore District Tourism Promotion Council',
    'https://indore.nic.in/en/tourist-place/janapav/',
    'Lush misty green peaks and valley overlook from Janapav Kuti summit',
    'District Administration Indore / MP Tourism',
    'Public Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km from Indore directly off Mumbai-Agra NH 52; steep paved winding road to summit.',
    '["Summit road has sharp curves; drive cautiously in heavy fog", "Panoramic 360-degree viewpoint overlooking Malwa plains", "Ayurvedic herbs and ashram atmosphere on hilltop"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000005',
    'Burhanpur Shahi Qila & Asirgarh Fortress',
    'burhanpur-asirgarh',
    'The historic ''Gateway to the Deccan'' featuring the invincible Asirgarh hilltop fort, Mughal bathhouses (Shahi Hammam), black stone Jama Masjid, and the unique underground Kundi Bhandara water system.',
    21.31,
    76.22,
    'Mughal Architecture & Massive Fort',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/b/b5/Asirgarh_Fort_Burhanpur_Madhya_Pradesh.jpg',
    'Archaeological Survey of India / MP Tourism',
    'https://burhanpur.nic.in/en/tourist-place/asirgarh-fort/',
    'Asirgarh hilltop stone fortress battlements overlooking Satpura valleys',
    'ASI Bhopal Circle / Burhanpur Tourism',
    'State Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '180 km from Indore via Sanawad & Khandwa (SH 27 / NH 347); smooth state highway.',
    '["Asirgarh fort is expansive; carry sun protection and comfortable walking shoes", "UNESCO tentative listed underground water labyrinth Kundi Bhandara is a must-see", "Sample authentic Burhanpuri Mawa Jalebi and Daraba sweet in local markets"]'::jsonb
),
(
    '22222222-0002-0002-0002-000000000006',
    'Gandhi Sagar Sanctuary & Hinglajgarh Fort',
    'gandhi-sagar',
    'An offbeat wildlife haven along the Chambal river reservoir in Mandsaur, featuring rock-cut temples, prehistoric rock art, Hinglajgarh forest citadel, and boat safaris for marsh crocodiles and leopards.',
    24.58,
    75.65,
    'Hidden Wildlife Sanctuary & Canyon',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/e/ec/Gandhi_Sagar_Dam_Mandsaur.jpg',
    'MP Tourism / Gandhi Sagar Festival',
    'https://www.mptourism.com/destination-gandhisagar.php',
    'Chambal river reservoir water canyons and wildlife forest edge at Gandhi Sagar',
    'MP Tourism Ecotourism Wing',
    'Official Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Mandsaur/Neemuch to Bhanpura via SH; rugged scenic landscape with paved access.',
    '["Annual Gandhi Sagar Floating Festival operates luxury tent cities and water sports", "Hire registered forest guides for rock art site visits", "Winter season (Nov-Feb) brings thousands of migratory aquatic birds"]'::jsonb
),
(
    'e5555555-5555-5555-5555-555555555555',
    'Bhedaghat & Marble Rocks',
    'bhedaghat',
    'Towering crystalline marble cliffs rising 100 feet on either side of the sacred Narmada River, creating the roaring Dhuandhar Falls, cable ropeway, and serene moonlight boat gorges.',
    23.1311,
    79.8006,
    'Geological Wonder & River Gorge',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/6/69/Dhuandhar_Falls_Bhedaghat_Jabalpur.jpg',
    'Jabalpur Tourism Promotion Council / MP Tourism',
    'https://www.mptourism.com/destination-bhedaghat.php',
    'Crystalline white marble cliffs and roaring water at Dhuandhar Falls, Bhedaghat',
    'MP Tourism Jabalpur Wing',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Fast 22 km highway drive from Jabalpur city center; broad bypass road with smooth tarmac.',
    '["Boating is suspended during peak monsoon flood currents (July-Sept)", "Full moon night boat rides through the marble canyon are extraordinarily popular", "Cable car ropeway connects both banks directly above Dhuandhar falls"]'::jsonb
),
(
    '77777777-7777-7777-7777-777777777777',
    'Kanha National Park & Tiger Reserve',
    'kanha',
    'Vast Sal forests and sweeping meadows that inspired Rudyard Kipling''s Jungle Book, hosting flourishing populations of Royal Bengal Tigers and the rare Hardground Barasingha (swamp deer).',
    22.3345,
    80.6115,
    'Wildlife Safari & Tiger Reserve',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/1/14/Tiger_Kanha_National_Park.jpg',
    'Kanha Tiger Reserve Field Directorate',
    'https://kanhatigerreserve.org/',
    'Royal Bengal tiger moving through open Sal meadows in Kanha National Park',
    'Kanha Tiger Reserve Authority / MP Forest',
    'Official Tiger Reserve Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Good state highway from Jabalpur (160 km) and Raipur; forest fringe roads require slow cautious driving.',
    '["Park closed July 1 to Sept 30 during annual breeding season", "Safari slots across Khatia, Mukki, and Sarhi gates must be booked in advance", "Morning safaris require early 5:30 AM reporting at designated gates"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000001',
    'Bandhavgarh National Park',
    'bandhavgarh',
    'Famous for having one of the highest densities of Royal Bengal Tigers in the world, centered around an ancient 2,000-year-old hilltop fort and reclining Vishnu rock sculpture (Shesh Shaiya).',
    23.7225,
    81.025,
    'Wildlife Safari & Ancient Citadel',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/8/87/Bandhavgarh_Tigress_in_Wild.jpg',
    'Bandhavgarh Tiger Reserve Authority',
    'https://forest.mponline.gov.in/',
    'Bandhavgarh cliff fortress backdrop with tiger habitat grasslands in foreground',
    'Bandhavgarh Field Directorate / MP Forest',
    'Official Reserve Source',
    '2026-08-21T06:00:00Z'::timestamptz,
    '165 km from Jabalpur via Katni / Umaria; 4-lane highway with good connectivity.',
    '["Tala, Magdhi, and Khitauli are the prime safari zones", "Pre-booking open gypsy vehicles is essential for tiger tracking", "Carry warm clothing during November-February morning safaris"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000002',
    'Pench National Park (Mowgli''s Land)',
    'pench',
    'The classic landscape of teak forests and the meandering Pench River, renowned for tiger tracking, leopard sightings, Indian wild dogs (Dhole), and wolf sanctuaries.',
    21.75,
    79.3,
    'Wildlife Safari & Ecotourism',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/e/ee/Pench_National_Park_Tiger_Safari.jpg',
    'Pench Tiger Reserve Directorate',
    'https://penchtiger.mponline.gov.in/',
    'Teak forest tree canopy and riverbed clearing in Pench National Park',
    'Pench Tiger Reserve Authority',
    'Official Park Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Directly accessible from Seoni and Nagpur via NH 44 (four-lane expressway with wildlife elevated corridor).',
    '["Turia and Karmajhiri are the most popular entry gates", "Night buffer safaris offer nocturnal wildlife viewing", "Check gate locations when booking lodging accommodations"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000003',
    'Amarkantak (Teerthraj / Source of Narmada)',
    'amarkantak',
    'The sacred meeting point of the Vindhya and Satpura ranges, source of the Holy Narmada and Son rivers, featuring the Narmadakund temple complex, Kapildhara waterfall, and Mai ki Bagiya.',
    22.67,
    81.75,
    'Sacred Source & Mountain Sanctuary',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/8/8f/Narmadakund_Temple_Complex_Amarkantak.jpg',
    'Amarkantak Temple Trust / MP Tourism',
    'https://www.mptourism.com/destination-amarkantak.php',
    'White-washed temple shrines surrounding the sacred Narmadakund in Amarkantak',
    'MP Tourism / Holy Shrine Board',
    'Pilgrimage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Scenic ghat road from Jabalpur (220 km) or Shahdol; pine tree lined hill ascent with smooth asphalt.',
    '["Temperatures remain pleasant year-round; carry light woolens in winter", "Kapildhara and Dudhadhara waterfalls require moderate walking downhill", "Visit Kabir Chabutra for sunset views across valley ridges"]'::jsonb
),
(
    '33333333-0003-0003-0003-000000000004',
    'Patalkot Valley & Tamia Hills',
    'patalkot-tamia',
    'A secluded 1,200-foot-deep horseshoe-shaped canyon in Chhindwara, home to indigenous Bharia tribes, 18 isolated villages, untouched flora, and rare ethno-medicinal herbs.',
    22.4,
    78.75,
    'Hidden Canyon & Tribal Eco-Heritage',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/0/03/Patalkot_Valley_Chhindwara.jpg',
    'Chhindwara District Administration / MP Tourism',
    'https://chhindwara.nic.in/en/tourist-place/patalkot/',
    'Deep dramatic green gorge and isolated tribal settlement basin in Patalkot Valley',
    'MP Ecotourism / Chhindwara Tribal Council',
    'Tribal Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '78 km northwest of Chhindwara via Tamia ghats; winding hill roads with breathtaking valley lookouts.',
    '["Hiring a local tribal guide is mandatory for descending into the valley basin", "Sunlight reaches the deep canyon floor only for a few hours around midday", "Tamia PWD Rest House offers one of MP''s best cliffside sunrise views"]'::jsonb
),
(
    'b2222222-2222-2222-2222-222222222222',
    'Khajuraho Group of Monuments',
    'khajuraho',
    'A world-renowned UNESCO World Heritage site known for magnificent Nagara-style architectural temples, intricate stone carvings, and the annual Khajuraho Dance Festival.',
    24.8318,
    79.9199,
    'UNESCO Heritage & Architecture',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/d/df/Kandariya_Mahadeva_Temple%2C_Khajuraho.jpg',
    'Archaeological Survey of India / UNESCO',
    'https://whc.unesco.org/en/list/240/',
    'Kandariya Mahadeva Temple Nagara shikhara and stone relief friezes in Khajuraho',
    'ASI / UNESCO World Heritage',
    'World Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'NH 39 four-lane highway connectivity from Jhansi and Chhatarpur; smooth transit suitable for all vehicles.',
    '["Western group of temples requires ASI entry ticket", "Light and Sound show operates in evening hours (English & Hindi)", "Summer temperatures can exceed 42°C; carry hydration and sun protection"]'::jsonb
),
(
    'f6666666-6666-6666-6666-666666666666',
    'Orchha Historic Royal Town',
    'orchha',
    'A frozen-in-time riverside kingdom founded in the 16th century, featuring the grand Jahangir Mahal, Raja Mahal, Ram Raja Temple (where Rama is worshipped as King), and riverside Chhatris.',
    25.351,
    78.6433,
    'Palatial Heritage & Riverside Culture',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/9/90/Jahangir_Mahal_Orchha_Madhya_Pradesh.jpg',
    'Madhya Pradesh State Archaeology / MP Tourism',
    'https://www.mptourism.com/destination-orchha.php',
    'Royal stone Chhatris and Jahangir Mahal reflected in the Betwa River in Orchha',
    'MP Tourism / Orchha Heritage',
    'State Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Easy 15 km drive from Jhansi railway hub; wide paved road connecting across the Betwa river.',
    '["River rafting and kayaking available on the Betwa in post-monsoon months", "Ram Raja Temple follows royal guard of honour salute during daily aarti", "Sound and light show inside Orchha Fort palace complex"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000001',
    'Gwalior Fort & Gopachal Rock Statues',
    'gwalior-fort',
    'Referred to as ''The Pearl in the necklace of forts of India'' by Babur, perched atop a steep sandstone hill with Man Mandir Palace, Sas Bahu Temples, Teli ka Mandir, and giant 7th-century rock-cut Jain Tirthankaras.',
    26.2295,
    78.167,
    'Hill Fortress & Ancient Citadel',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/e/e0/Gwalior_Fort_Man_Mandir_Palace.jpg',
    'Archaeological Survey of India / Gwalior Heritage',
    'https://gwalior.nic.in/en/tourist-place/gwalior-fort/',
    'Man Mandir Palace sandstone battlements and ornate turquoise tile frieze at Gwalior Fort',
    'ASI / MP Tourism',
    'National Monument Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Direct 6-lane NH 44 connectivity; smooth uphill climb to the fort gate from Urvai Gate or Gwalior Gate.',
    '["Urvai Gate ascent allows driving cars up to the fort summit parking", "Visit Jai Vilas Palace and Scindia Museum in the city below", "Evening sound and light show narrated by Amitabh Bachchan"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000005',
    'Chanderi Heritage Town & Weaving Cluster',
    'chanderi',
    'An ancient fortified town surrounded by hills and lakes, celebrated for handwoven Chanderi silk sarees, the grand Koshak Mahal, Badal Mahal Gate, and the hilltop Chanderi Fort.',
    24.715,
    78.135,
    'Silk Weaving Heritage & Fortified Town',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/a/a2/Badal_Mahal_Gate_Chanderi.jpg',
    'Chanderi Handloom Weavers Guild / MP Tourism',
    'https://www.mptourism.com/destination-chanderi.php',
    'Badal Mahal monumental stone gateway with hilltop Chanderi fort in background',
    'MP Tourism / Chanderi Craft Council',
    'Craft & Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    '110 km from Jhansi / 210 km from Bhopal via Lalitpur or Ashoknagar; good state highways.',
    '["Explore Pranpur craft village for live traditional loom demonstrations", "Chanderi Fort offers stunning sunset views over the whitewashed historic town", "Chanderi Museum preserves exquisite sculptures and ancient coins"]'::jsonb
),
(
    '44444444-0004-0004-0004-000000000007',
    'Panna National Park & Diamond Mines',
    'panna-tiger-reserve',
    'A successful tiger conservation story along the Ken River gorge, known for boat safaris, tree-nesting vulture colonies, pristine Pandav Falls, and India''s only active diamond mining belt.',
    24.65,
    80.05,
    'Tiger Reserve, Gorge & Diamond Valley',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/5/52/Ken_River_Panna_National_Park.jpg',
    'Panna Tiger Reserve Directorate',
    'https://forest.mponline.gov.in/',
    'Ken river flowing through rocky gorges in Panna Tiger Reserve',
    'Panna Field Directorate / MP Forest',
    'Tiger Reserve Official',
    '2026-08-21T06:00:00Z'::timestamptz,
    '45 km from Khajuraho via NH 39; smooth tarmac road right to Madla entrance gate.',
    '["Madla and Hinouta gates provide deep forest safari access", "Boat ride on the Ken River within the park offers unique crocodile sightings", "Combine with Pandav Falls caves on the same circuit"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000001',
    'Junapani Waterfall & Forest Trail',
    'junapani',
    'A serene monsoon eco-tourism getaway near Indore featuring seasonal streams, natural rock pools, verdant forest trails, and tranquil picnic clearings away from crowded tourist circuits.',
    22.4862,
    75.8234,
    'Monsoon Waterfall & Forest Trail',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/e/ec/Waterfall_in_forest_monsoon_stream.jpg',
    'Indore Ecotourism Promotion Council',
    'https://indore.nic.in/',
    'Cascading forest streams and natural pools at Junapani',
    'MP Ecotourism Wing',
    'Public Domain / Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 35 km from Indore via Mhow-Manpur highway; the final 3 km involves an unpaved forest track. Vehicles with higher ground clearance recommended.',
    '["Seasonal flow is strongest during peak monsoon (July to September)", "Avoid climbing wet, mossy boulders near the water edge", "Carry water and snacks as local vendor stalls are limited"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000002',
    'Lodhiya Kund Waterfall',
    'lodhiya-kund',
    'A hidden natural plunge pool and cascading waterfall nestled in the valley near Manpur, offering a picturesque picnic and trekking spot bordered by rugged rocks and dense flora.',
    22.4215,
    75.6421,
    'Hidden Waterfall & Trekking',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/4/4b/Plunge_pool_waterfall_canyon.jpg',
    'Madhya Pradesh Ecotourism Board',
    'https://indore.nic.in/',
    'Scenic waterfall and rocky natural plunge pool at Lodhiya Kund',
    'Indore District Administration',
    'State Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 50 km from Indore via AB Road (NH 52) towards Manpur; last 2 km requires gentle off-road driving and a short 15-minute downhill hike.',
    '["Water depth in the central kund can be deceptively deep; swimming is not advised without life jackets", "Wear trekking shoes with strong grip for navigating gravel slopes", "Depart before sunset as the route lacks night lighting"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000003',
    'Mohadi Valley (Muhadi Falls)',
    'mohadi-valley',
    'A scenic canyon and cascading waterfall set amid the lush green hills of the Vindhyan range near Tinchha, perfect for nature photography, morning hikes, and peaceful valley views.',
    22.5684,
    75.9612,
    'Scenic Valley & Nature Hike',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/3/3d/Mohadi_Waterfall_Indore.jpg',
    'MP Tourism / Ecotourism Board',
    'https://indore.nic.in/',
    'Expansive green valley views and misty streams in Mohadi Valley',
    'MP Tourism Ecotourism Wing',
    'Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 30 km from Indore via Ralamandal and Tillor Khurd road; paved rural road leading to a scenic viewpoint trail.',
    '["Trek down to the waterfall base can be slippery after rainfall", "Stay on designated trail ridges to avoid steep loose rock edges", "Ideal morning drive destination during monsoon and early winter"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000004',
    'Kalakund Forest & Heritage Railway Valley',
    'kalakund',
    'A lush valley along the Choral River famous for dense teak forest trails, the historic Patalpani-Kalakund metre-gauge heritage railway train ride, and its authentic regional specialty sweet—Kalakund.',
    22.4578,
    75.8236,
    'Heritage Railway & River Valley',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/4/41/Patalpani_Kalakund_Heritage_Railway_Line.jpg',
    'Western Railway Heritage / MP Tourism',
    'https://www.mptourism.com/',
    'Heritage train corridor and lush river valley at Kalakund',
    'Western Railway / MP Tourism',
    'Public Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 40 km from Indore via Mhow; accessible by road or via the scenic weekend heritage train from Patalpani.',
    '["Weekend heritage train tickets should be reserved via IRCTC in advance during monsoon", "Check river water levels before crossing low-lying culverts during heavy downpours", "Do not walk across active railway tunnels and trestle bridges on foot"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000005',
    'Jam Gate (Vindhyachal Gateway)',
    'jam-gate',
    'A historic 18th-century stone gateway built by Maharani Ahilyabai Holkar standing perched atop the Vindhya ridge (800m), renowned for panoramic cloud inversions, sunrise views, and dramatic mountain ghats.',
    22.3685,
    75.7618,
    'Historical Viewpoint & Mountain Ghat',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/1/18/Jam_Gate_Mhow_Indore.jpg',
    'Khargone Tourism / Ahilya Heritage',
    'https://khargone.nic.in/',
    'Historic Jam Gate stone archway overlooking misty mountain valley',
    'MP Tourism / District Administration',
    'Heritage Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 55 km from Indore via Mhow-Mandleshwar ghat road; scenic multi-hairpin mountain pass with smooth asphalt tarmac.',
    '["Exercise caution when driving through thick fog or low-visibility clouds during morning hours", "Use low gears on the steep descent towards Mandleshwar", "Early morning sunrise (5:30 AM to 7:00 AM) provides optimal cloud cover vistas"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000006',
    'Sahastradhara (Thousand Streams)',
    'sahastradhara-maheshwar',
    'A natural wonder on the Narmada River near Maheshwar where the wide river breaks over jagged volcanic rock into a thousand rushing whitewater channels and tranquil rock pools.',
    22.1645,
    75.5412,
    'River Rapids & Geological Marvel',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/8/87/Sahastradhara_Maheshwar_Narmada_Rapids.jpg',
    'MP Tourism / Maheshwar Heritage',
    'https://www.mptourism.com/destination-maheshwar.php',
    'Narmada river dividing into multiple channels over volcanic rock formations at Sahastradhara',
    'MP Tourism Khargone Wing',
    'Tourism Board Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 5 km upstream from Maheshwar Fort; accessible via boat ride or a short paved country road connecting to the rocky bank.',
    '["River currents in the narrow rock channels are strong; avoid swimming across deep channels", "Hire motorized wooden boats from Maheshwar ghats for scenic river access", "Volcanic rocks can be sharp and uneven; wear sturdy sandals or shoes"]'::jsonb
),
(
    '55555555-0005-0005-0005-000000000007',
    'Lotus Valley (Gulawat Lotus Lake)',
    'lotus-valley-gulawat',
    'A sprawling backwater lake near Yashwant Sagar completely blanketed with blooming pink lotus flowers and shaded by dense bamboo groves, featuring picturesque wooden bridges and boating channels.',
    22.7915,
    75.7125,
    'Seasonal Lake & Eco-Retreat',
    'Madhya Pradesh',
    'https://upload.wikimedia.org/wikipedia/commons/8/8e/Gulawat_Lotus_Valley_Indore.jpg',
    'Indore District Administration / MP Tourism',
    'https://indore.nic.in/',
    'Blooming pink lotus flowers and bamboo walkway at Gulawat Lotus Valley',
    'District Administration Indore',
    'Public Domain / Tourism Verified',
    '2026-08-21T06:00:00Z'::timestamptz,
    'Approx 30 km from Indore via Airport Road & Hatod; well-paved rural approach road with on-site visitor parking.',
    '["Peak blooming season is from October through February; winter mornings offer optimal views", "Traditional wooden boat rides operate along narrow channels cut through the lotus pads", "Early morning sunrise is ideal for avoiding afternoon crowds and catching the flowers open"]'::jsonb
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    category = EXCLUDED.category,
    region = EXCLUDED.region,
    hero_image_url = EXCLUDED.hero_image_url,
    image_source = EXCLUDED.image_source,
    image_source_url = EXCLUDED.image_source_url,
    image_alt = EXCLUDED.image_alt,
    image_credit = EXCLUDED.image_credit,
    image_license = EXCLUDED.image_license,
    image_verified_at = EXCLUDED.image_verified_at,
    road_condition = EXCLUDED.road_condition,
    safety_tips = EXCLUDED.safety_tips,
    updated_at = NOW();
